apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-lb
spec:
  scaleTargetRef:
    apiVersion: nginx/latest
    kind: deployment
    name: nginx-lb
  minReplicas: 10
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
