apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-lb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-lb
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
