apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: HTTP
      port: 80
      targetPort: 80
    selector:
      application: fe-nginx
