apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: nginx-lb
  template:
    metadata:
      labels:
        application: nginx-lb
    spec:
      containers:
        - name: nginx-lb-pod
          image: myregistry.net/nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
          requests:
            cpu: 100m
            memory: 100Mi
