apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      application: nginx-lb
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
        - name: nginx-lb-pod
          image: myregistry.net/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
          requests:
            cpu: 100m
            memory: 100Mi
