apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
  labels:
    application: fe-nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      application: fe-nginx
  template:
    metadata:
      labels:
        application: fe-nginx
    spec:
      containers:
        - name: nginx-lb
          #image: myregistry.net/nginx:latest
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
