apiVersion: apps/v1
kind: deployment
metadata:
  name: nginx-lb
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: myregistry.net/nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
