apiVersion: apps/v2
kind: Deployment
metadata:
  name: nginx-lb
spec:
  selector:
    matchLabels:
      app: nginx-lb
  replicas: 24
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
        - name: nginx
          image: myregistry.net/nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
