apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
  labels:
    application: fe-nginx
spec:
  selector:
  replicas: 24
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        application: fe-nginx
    spec:
      containers:
        - name: nginx-lb
          image: myregistry.net/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
