apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombardier
  labels:
    application: bombardier
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      application: bombardier
  template:
    metadata:
      labels:
        application: bombardier
    spec:
      containers:
        - name: bombardier
          image: bombardier:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
