apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bombardier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bombardier
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80