- hosts: all
  become: yes
  tasks:
    - name: remove Docker
      yum:
        name: docker
        state: absent
        update_cache: true

    - name: remove kubelet
      yum:
        name: kubelet
        state: absent
        update_cache: true

    - name: Rebooting ...
      command: shutdown -r now "Reboot required for updated kernel"
            async: 0
            poll: 0
            ignore_errors: true
            changed_when: "reboot_hint.stdout == 'reboot'"
            register: rebooting

    - name: Wait for computer to reboot...
        pause: seconds=180
        when: rebooting|changed

    - name: remove Folders lib
      shell: rm -rf /var/lib/docker /var/lib/dockershim

    - name: remove Folders etc
      shell: rm -rf /etc/docker /etc/kubernetes

    - name: remove file
      shell: rm -rf /root/*.txt

- hosts: master
  become: yes
  tasks:
    - name: remove files
      shell: rm -rf /home/centos/.kub/* /home/centos/*.txt

    - name: remove folders
      shell: rm -rf /var/lib/kubelet /var/lib/etcd

