- hosts: all
  become: yes
  tasks:
    - name: remove Docker
      yum:
        name: docker
        state: absent
        update_cache: true

    - name: remove kubelet
      yum:
        name: kubelet
        state: absent
        update_cache: true

    - name: Reboot servers
      command: /sbin/reboot

    - name: Wait for the servers to finish rebooting
      sudo: no
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300

    - name: remove Folders lib
      shell: rm -rf /var/lib/docker /var/lib/dockershim


    - name: remove Folders etc
      shell: rm -rf /etc/docker /etc/kubernetes


    - name: remove file
      shell: rm -rf /root/*.txt


- hosts: master
  become: yes
  tasks:
    - name: remove files
      shell: rm -rf /home/centos/.kube/* /home/centos/*.txt

    - name: remove folders
      shell: rm -rf /var/lib/kubelet /var/lib/etcd

    - name: remove Folders lib
      shell: rm -rf /var/lib/docker /var/lib/dockershim



