- hosts: all
  become: yes
  tasks:
    - name: remove Docker
      yum:
        name: docker
        state: absent
        update_cache: true

    - name: remove kubelet
      yum:
        name: kubelet
        state: absent
        update_cache: true

    - name: Restart machine
      shell: "sleep 5 && sudo shutdown -r now"
      async: 1
      poll: 0

    - name: wait for ssh again available.
      wait_for_connection:
        delay: 5
        timeout: 300


    - name: remove Folders lib
      shell: rm -rf /var/lib/docker /var/lib/dockershim
      warn: false

    - name: remove Folders etc
      shell: rm -rf /etc/docker /etc/kubernetes
      warn: false

    - name: remove file
      shell: rm -rf /root/*.txt
      warn: false

- hosts: master
  become: yes
  tasks:
    - name: remove files
      shell: rm -rf /home/centos/.kub/* /home/centos/*.txt

    - name: remove folders
      shell: rm -rf /var/lib/kubelet /var/lib/etcd

