- hosts: all
  become: yes
  tasks:
    - name: remove Docker
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        state: absent
        update_cache: true
        
    - name: remove docker-common
      yum:
        name: docker-common
        state: absent
        update_cache: true
        
    - name: remove containerd-io
      yum:
        name: containerd.io
        state: absent
        update_cache: true

    - name: remove kubelet
      yum:
        name: kubelet
        state: absent
        update_cache: true

    - name: remove kubectl
      yum:
        name: kubectl
        state: absent
        update_cache: true


    - name: Reboot the servers
      reboot:
        reboot_timeout: 60

    - name: waiting servers
      local_action: wait_for host="{{ansible_host}}" delay=60 state=started port=22 connect_timeout=60 timeout=180

    - name: remove Folders docker
      file:
        path: /var/lib/docker
        state: absent

    - name: emove Folders dockershim
      file:
        path: /var/lib/dockershim
        state: absent

    - name: remove Folders etc/docker
      file:
        path: /etc/docker
        state: absent

    - name: remove Folders etc/kubernetes
      file:
        path: /etc/kubernetes
        state: absent

    - name: remove file cluster.txt
      file:
        path: /root/cluster_initialized.txt
        state: absent

    - name: remove file node_joined.txt
      file:
        path: /root/node_joined.txt
        state: absent

    - name: remove pod_network_setup.txt
      file:
        path: /root/pod_network_setup.txt
        state: absent

    - name: remove Folder .kube
      file:
        path: $HOME/.kube
        state: absent

- hosts: master
  become: yes
  tasks:
    - name: remove folders kubelet
      file:
        path: /var/lib/kubelet
        state: absent

    - name: remove folder etcd
      file:
        path: /var/lib/etcd
        state: absent

    - name: remove Folders lib docker
      file:
        path: /var/lib/docker
        state: absent

    - name: remove Folders lib dockershim
      file:
        path: /var/lib/dockershim
        state: absent





