- hosts: all
  become: yes
  tasks:
    - name: remove Docker
      yum:
        name: docker
        state: absent
        update_cache: true

    - name: remove kubelet
      yum:
        name: kubelet
        state: absent
        update_cache: true

    - name: remove kubectl
      yum:
        name: kubectl
        state: absent
        update_cache: true


    - name: Reboot the servers
      reboot:
        reboot_timeout: 60

    - name: waiting servers
      local_action: wait_for host="{{ansible_host}}" delay=60 state=started port=22 connect_timeout=60 timeout=180

    - name: Kill all Process
      shell: ps -ef | grep 'pause' | grep -v grep | awk '{print $2}' | xargs -r kill -9

    - name: remove Folders lib
      shell: rm -rf /var/lib/docker /var/lib/dockershim


    - name: remove Folders etc
      shell: rm -rf /etc/docker /etc/kubernetes


    - name: remove file
      shell: rm -rf /root/*.txt


- hosts: master
  become: yes
  tasks:
    - name: remove files
      shell: rm -rf /home/centos/.kube/* /home/centos/*.txt

    - name: remove folders
      shell: rm -rf /var/lib/kubelet /var/lib/etcd

    - name: remove Folders lib
      shell: rm -rf /var/lib/docker /var/lib/dockershim



