- hosts: all
  become: yes
  tasks:
    - name: Power-off
      become_user: root
      shell: /sbin/shutdown -h now
      
    - name: wait go down l
      local_action: wait_for host="{{ansible_host}}" delay=10 state=stopped port=22
   

