- hosts: all
  become: yes
  tasks:
    - name: "Upgrade all yum packages."
      yum:
        name: "*"
        state: latest
    - name: check for reboot hint
      shell: if [ $(rpm -q --last kernel | awk 'NR==1 {print $1}') != kernel-$(uname -r) ]; then echo 'reboot'; else echo 'Kernel is current'; fi
      ignore_errors: true
      register: reboot_hint

    - name: Restart machine
      shell: "sleep 5 && sudo shutdown -r now"
      async: 1
      poll: 0

    - name: wait for ssh again available.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300