- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command > $HOME/join_command

    - name: share join command
      copy:
        src: join_command
        dest: /opt/kuber-volume/join_command.sh
        mode: 0777

- hosts: workers
  become: yes
  tasks:
    - name: join to cluster
      command: sh /opt/kuber-volume/join_command.sh