- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command > /opt/kuber-volume/join_command.sh

- hosts: workers
  become: yes
  tasks:
    - name: join to cluster
      shell: sh /opt/kuber-volume/join_command.sh