- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command > $HOME/join_command

    - name: share join command
      copy:
        src: $HOME/join_command
        dest: /opt/kuber-volume/join_command.sh
        remote_src: yes
        mode: 0777

- hosts: workers
  become: yes
  tasks:
    - name: reset Cluster after ADD
      shell: kubeadm reset
        arg:
          warn: yes

    - name: join to cluster
      shell: sh /opt/kuber-volume/join_command.sh