- hosts: all
  become: yes
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: check for reboot hint
      shell: if [ $(rpm -q --last kernel | awk 'NR==1 {print $1}') != kernel-$(uname -r) ]; then echo 'reboot'; else echo 'Kernel is current'; fi
      ignore_errors: true
      register: reboot_hint

    - name: Reboot the servers
      reboot:
        reboot_timeout: 60

    - name: waiting servers
      local_action: wait_for host="{{ansible_host}}" delay=60 state=started port=22 connect_timeout=60 timeout=180