- hosts: all
  become: yes
  tasks:
    - name: Clean up incomplete yum transactions
      shell: yum-complete-transaction --cleanup-only -y
      register: yum_cleanup_output
      changed_when: "'Nothing to do' not in yum_cleanup_output.stdout"
      ignore_errors: yes

    - name: Debug yum cleanup output
      debug:
        var: yum_cleanup_output.stdout

    - name: Remove Docker and Kubernetes-related packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - kubelet
          - kubectl
        state: absent
        update_cache: true

    - name: Remove additional Docker packages
      yum:
        name: docker-common
        state: absent
        update_cache: true

    - name: Stop and disable kubelet service
      service:
        name: kubelet
        state: stopped
        enabled: no

    - name: Flush IPTables rules (Kubernetes-related)
      shell: |
        iptables -F
        iptables -t nat -F
        iptables -t mangle -F
        iptables -X
      ignore_errors: yes

    - name: Reboot the servers
      reboot:
        reboot_timeout: 60

    - name: Remove residual directories and files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /var/lib/dockershim
        - /etc/docker
        - /etc/kubernetes
        - /root/cluster_initialized.txt
        - /root/node_joined.txt
        - /root/pod_network_setup.txt
        - "{{ ansible_env.HOME }}/.kube"

- hosts: master
  become: yes
  tasks:
    - name: Remove Kubernetes master-specific directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/kubelet
        - /var/lib/etcd
        - /var/lib/docker
        - /var/lib/dockershim

    - name: Debug completion message
      debug:
        msg: "Cleanup completed for master nodes."
