- hosts: all
  become: yes
  tasks:
    - name: install nfs-utils
      yum:
        name: nfs-utils
        state: present
        update_cache: true

    - name: start nfs
      service:
        name: nfs-server
        enabled: yes
        state: restarted


