- hosts: all
  become: yes
  tasks:
    - name: add Docker YUM repository
      become: yes
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        
    - name: upgrade all packages, excluding kernel & foo related packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*
        
    - name: install docker-ce
      yum:
        name: docker-ce
        state: present
        update_cache: true
        
    - name: install containerd-io
      yum:
        name: containerd.io
        state: present
        update_cache: true
        
    - name: install docker-ce-cli
      yum:
        name: docker-ce-cli
        state: present
        update_cache: true
        
      
