- hosts: all
  become: yes
  vars:
    zabbix_version: "5.0"
    zabbix_server_ip: "192.168.1.50"

  tasks:
    - name: Ensure Python3 and dependencies are installed
      block:
        - name: Install Python 3 and pip
          raw: |
            apt-get update && apt-get install -y python3 python3-pip python3-apt

        - name: Ensure Python 3 interpreter for Ansible
          ansible.builtin.setup:

      rescue:
        - name: Fail task with error message
          fail:
            msg: "Failed to install Python3 or its dependencies."

    - name: Install prerequisites for Zabbix Agent
      apt:
        name:
          - wget
          - gnupg
        state: present
        update_cache: yes

    - name: Add Zabbix repository
      shell: |
        wget https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1%2Blunar_all.deb
        dpkg -i zabbix-release_{{ zabbix_version }}-1+lunar_all.deb
        apt-get update
      args:
        creates: /etc/apt/sources.list.d/zabbix.list

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^Server=", line: "Server={{ zabbix_server_ip }}" }
        - { regexp: "^ServerActive=", line: "ServerActive={{ zabbix_server_ip }}" }
        - { regexp: "^Hostname=", line: "Hostname={{ inventory_hostname }}" }

    - name: Restart and enable Zabbix Agent service
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes

    - name: Verify Zabbix Agent service status
      shell: systemctl is-active zabbix-agent
      register: zabbix_status
      failed_when: "'active' not in zabbix_status.stdout"

    - name: Debug Zabbix Agent status
      debug:
        var: zabbix_status.stdout
