- hosts: all
  become: yes
  tasks:
    - name: Add Docker YUM repository
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        executable: /bin/bash

    - name: Upgrade all packages, excluding kernel
      yum:
        name: '*'
        state: latest
        exclude: kernel*

    - name: Install Docker and dependencies
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Configure Docker Daemon
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "storage-driver": "overlay2"
          }
        mode: 0644

    - name: Restart Docker
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Check Docker service status
      shell: systemctl status docker
      register: docker_status
      failed_when: "'active (running)' not in docker_status.stdout"

    - name: Debug Docker service output
      debug:
        var: docker_status.stdout
