- hosts: all
  become: yes
  tasks:
    - name: Install containerd dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install containerd.io
      yum:
        name: containerd.io
        state: present
        update_cache: true

    - name: Create containerd configuration file
      shell: |
        containerd config default > /etc/containerd/config.toml

    - name: Update containerd configuration (use systemd as cgroup driver)
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        line: 'SystemdCgroup = true'

    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes

    - name: Debug containerd status
      shell: systemctl status containerd
      register: containerd_status
      failed_when: "'active (running)' not in containerd_status.stdout"

    - name: Display containerd status
      debug:
        var: containerd_status.stdout
