- hosts: all
  become: yes
  vars:
    zabbix_version: "5.0"
    zabbix_server_ip: "192.168.1.50"

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - wget
          - gnupg
        state: present
        update_cache: yes

    - name: Add Zabbix repository
      shell: |
        wget https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1%2Blunar_all.deb
        dpkg -i zabbix-release_{{ zabbix_version }}-1+lunar_all.deb
      args:
        creates: /etc/apt/sources.list.d/zabbix.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^Server=", line: "Server={{ zabbix_server_ip }}" }
        - { regexp: "^ServerActive=", line: "ServerActive={{ zabbix_server_ip }}" }
        - { regexp: "^Hostname=", line: "Hostname={{ inventory_hostname }}" }

    - name: Restart and enable Zabbix Agent service
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes

    - name: Verify Zabbix Agent service status
      command: systemctl status zabbix-agent
      register: zabbix_status
      failed_when: "'active (running)' not in zabbix_status.stdout"
      ignore_errors: yes

    - name: Debug Zabbix Agent status
      debug:
        var: zabbix_status.stdout
