- hosts: master
  become: yes
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:
        name: kubernetes-dashboard
        api_version: v1
        kind: Namespace
        state: present
