- hosts: master
  become: yes
  tasks:
    - name: reset Cluster after ADD
      shell: kubeadm reset -f

    - name: initialize the cluster
      shell: kubeadm init --apiserver-advertise-address=192.168.1.90 --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: root
      file:
        path: /root/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        mode: 0777

    - name: Synchronization config to the remote hosts
      become: yes
      shell: rsync -acP /root/.kube/ /opt/kuber-volume/.kube/

    - name: install Pod network
      become: yes
      shell: kubectl apply -f https://docs.projectcalico.org/v3.19/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

- hosts: workers
  become: yes
  tasks:
    - name: rsync conf
      become: yes
      shell: rsync -acP /opt/kuber-volume/.kube/ $HOME/.kube/

