- hosts: master
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
      register: init_output
      failed_when: "'error' in init_output.stderr or init_output.rc != 0"

    - name: Save initialization output to a file
      copy:
        content: "{{ init_output.stdout }}"
        dest: /root/cluster_initialized.txt
        mode: 0644  
    
    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        mode: 0644

    - name: Synchronize config to the remote hosts
      shell: rsync -acP /root/.kube/ /opt/kuber-volume/.kube/

    - name: Install Pod network with Flannel
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        chdir: $HOME
      register: flannel_output
      failed_when: "'error' in flannel_output.stderr or flannel_output.rc != 0"
      
    - name: Save Pod network setup log
      copy:
        content: "{{ flannel_output.stdout }}"
        dest: /root/pod_network_setup.txt
        mode: 0644
        
- hosts: workers
  become: yes
  tasks:
    - name: Synchronize kube config
      shell: rsync -acP /opt/kuber-volume/.kube/ $HOME/.kube/

    - name: Join worker nodes to the cluster
      shell: kubeadm join {{ master_ip }}:6443 --token {{ token }} --discovery-token-ca-cert-hash sha256:{{ ca_hash }}
      register: join_output
      failed_when: "'error' in join_output.stderr or join_output.rc != 0"

    - name: Save join output to a file
      copy:
        content: "{{ join_output.stdout }}"
        dest: /root/node_joined.txt
        mode: 0644
