- hosts: all
  become: yes
  tasks:
    - name: install runc
      yum:
        name: runc
        state: present
        update_cache: true

    - name: install psmisc
      yum:
        name: psmisc
        state: present
        update_cache: true

    - name : install Git
      yum:
        name: git
        state: present
        update_cache: true

    - name: restart Docker
      become: yes
      shell: systemctl restart docker && systemctl enable docker

    - name: net.ipv4.ip_forward is set to 1
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes

    - name: install kubelet & kubeadm
      become: yes
      shell: yum -y install kubelet kubeadm --disableexcludes=kubernetes


    - name: config Docker
      become: yes
      shell: rsync -acP /opt/kuber-volume/daemon.json /etc/docker/
        
    - name: defoult config for containerd
      become: yes
      shell: rm -rf /etc/containerd/config.toml
      
    - name: defoult config for containerd
      become: yes
      shell: containerd config default
      
    - name: restart containerd
      service:
        name: containerd
        enabled: yes
        state: restarted


- hosts: master
  become: yes
  tasks:       
    - name: install kubectl
      become: yes
      shell: yum -y install kubectl --disableexcludes=kubernetes
