- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - runc
          - psmisc
          - git
        state: present
        update_cache: true

    - name: Enable net.bridge.bridge-nf-call-* settings
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
        - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
        - { name: net.ipv4.ip_forward, value: 1 }
      register: sysctl_output

    - name: Reload sysctl
      shell: sysctl -p

    - name: Add Kubernetes repository
      yum_repository:
        name: kubernetes
        description: Kubernetes Repository
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.22/rpm/
        gpgcheck: yes
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.22/rpm/repodata/repomd.xml.key
        enabled: yes
        repo_gpgcheck: yes
        state: present
        
    - name: Remove old Kubernetes packages
      yum:
        name:
          - kubelet
          - kubectl
          - kubeadm
        state: absent

    - name: Update Kubernetes packages
      yum:
        name:
          - kubelet
          - kubectl
          - kubeadm
        state: latest
        update_cache: true

    - name: Enable and start kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: Ensure containerd is running
      service:
        name: containerd
        state: started
        enabled: true
