- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - runc
          - psmisc
          - git
        state: present
        update_cache: true

    - name: Enable net.bridge.bridge-nf-call-* settings
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
        - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
        - { name: net.ipv4.ip_forward, value: 1 }
      register: sysctl_output

    - name: Reload sysctl
      shell: sysctl -p

    - name: Install kubeadm, kubelet, kubectl
      shell: |
        cat <<EOF > /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
        EOF
        yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
      args:
        executable: /bin/bash

    - name: Enable and start kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

- hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes Cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init_output

    - name: Save cluster initialization output
      copy:
        content: "{{ kubeadm_init_output.stdout }}"
        dest: /opt/kuber-volume/cluster_initialized.txt
        mode: '0644'
