- hosts: localhost
  become: true
  tasks:
  - name:  your "{{ SERVICE_NAME }} will be {{ STATE }}"
    service:
      name: "{{ SERVICE_NAME }}"
      state: "{{ STATE }}"

  - name: Service status
    service:
      name: "{{ SERVICE_NAME }}"
      state: status
