- hosts: localhost
  become: true
  tasks:
  - name:  your "{{ SERVICE_NAME }} will be {{ STATE }}"
    service:
      name: "{{ SERVICE_NAME }}"
      state: "{{ STATE }}"
    register: service_output

  - name: Service status
    service:
      name: "{{ SERVICE_NAME }}"
      shell: systemctl status "{{ SERVICE_NAME }}"
