- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_command_output

    - name: Save join command to a file
      copy:
        content: "{{ join_command_output.stdout }}"
        dest: /opt/kuber-volume/join_command.sh
        mode: '0777'

- hosts: workers
  become: yes
  tasks:
    - name: reset Cluster after ADD
      shell: kubeadm reset -f

    - name: join to cluster
      shell: sh /opt/kuber-volume/join_command.sh
