- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command > $HOME/join_command

    - name: share join command
      copy:
        src: $HOME/join_command
        dest: /opt/kuber-volume/join_command.sh
        remote_src: yes
        mode: 0777

- hosts: workers
  become: yes
  tasks:
    - name: reset Cluster after ADD
      shell: kubeadm reset -f

    - name: join to cluster
      shell: sh /opt/kuber-volume/join_command.sh
      
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: install metrics
      shell: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
